<a href="https://colab.research.google.com/github/aioakiddnh/udemy_lecture_pytorch/blob/master/section1/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor
TensorはPyTorchにおいて最も基本となるデータ構造です。  
今回は、Tensorを生成したり、Tensor同士の計算をしたりするコードを練習します。

## パッケージの確認
インストール済みのパッケージを全て表示します。  
PyTorch（torch）がインストールされていることを確認しましょう。

In [1]:
!pip list

Package                  Version        
------------------------ ---------------
absl-py                  0.9.0          
alabaster                0.7.12         
albumentations           0.1.12         
altair                   4.1.0          
argon2-cffi              20.1.0         
asgiref                  3.2.10         
astor                    0.8.1          
astropy                  4.0.1.post1    
astunparse               1.6.3          
atari-py                 0.2.6          
atomicwrites             1.4.0          
attrs                    19.3.0         
audioread                2.1.8          
autograd                 1.3            
Babel                    2.8.0          
backcall                 0.2.0          
beautifulsoup4           4.6.3          
bleach                   3.1.5          
blis                     0.4.1          
bokeh                    2.1.1          
boto                     2.49.0         
boto3                    1.14.33        
botocore        

## Tensorの生成
torchのtensor関数によりTensorを生成します。  
以下のセルではPythonのリストからTensorを生成します。  
また、type( )により型を確認します。  

In [24]:
#pytorchをインポート #torchという名前でpytorchの様々な機能を使う事が出来る。
import torch

#pythonのリスト[1,2,3]をpytorchのtensor型に変換
a = torch.tensor([1,2,3])

print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


他にも、様々な方法でTensorを生成することができます。

In [5]:
# 2重のリストから生成
b = torch.tensor([[1, 2],
                  [3, 4]])
print(b)

# dtypeを指定し、倍精度のTensorにする
c = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float64)
print(c)

# 0から9まで(0以上10未満)の数値で初期化
d = torch.arange(0, 10)
print(d)

# すべての値が0の、2×3のTensor
e = torch.zeros(2, 3)
print(e)

# すべての値が乱数の、2×3のTensor
f = torch.rand(2, 3)
print(f)

# Tensorの形状はsizeメソッドで取得
print(f.size())

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4930, 0.5235, 0.9121],
        [0.1154, 0.3974, 0.4563]])
torch.Size([2, 3])


## TensorとNumPyの配列の変換
numpy()メソッドでTensorをNumPyの配列に変換することができます。  
また、from_numpy( )関数でNumPyの配列をTensorに変換することができます。

In [6]:
# Tensor → NumPy
a = torch.tensor([[1, 2],
                  [3, 4]])

# tensorからnumpyの配列に変換
b = a.numpy()
print(b)

# NumPy → Tensor
c = torch.from_numpy(b)
print(c)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


## 範囲を指定してアクセス
様々な方法で、Tensorの要素に範囲を指定してアクセスすることができます。

In [15]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# 2つのインデックスを指定
print(a[0, 1])

# 範囲を指定 
# a[行, 列]  # 行：1以上2未満、列：2未満
print(a[1:2, :2])

# リストで複数のインデックスを指定
# 「：」すべて #[0, 2] 0列目と2列目
print(a[:, [0, 2]])

# 3より大きい要素のみを指定
print(a[a>3])

# 要素の変更
a[0, 2] = 11
print(a)

# 要素の一括変更
a[:, 1] = 22
print(a)

# 10より大きい要素のみ変更
a[a>10] = 33
print(a)

tensor(2)
tensor([[4, 5]])
tensor([[1, 3],
        [4, 6]])
tensor([4, 5, 6])
tensor([[ 1,  2, 11],
        [ 4,  5,  6]])
tensor([[ 1, 22, 11],
        [ 4, 22,  6]])
tensor([[ 1, 33, 33],
        [ 4, 33,  6]])


## Tensorの演算
Tensorによりベクトルや行列を表現することができます。  
これらの演算は、一定のルールに基づき行われます。  

In [21]:
# ベクトル
a = torch.tensor([1, 2, 3]) #1×3
b = torch.tensor([4, 5, 6]) #1×3

# 行列
c = torch.tensor([[6, 5, 4],
                  [3, 2, 1]]) #2×3


# ベクトルとスカラーの演算 # aの全ての要素に3が足される
print(a + 3)

# ベクトル同士の演算 # aとbの各要素同士を足し合わせる
print(a + b)

# 行列とスカラーの演算 # cの各要素に2が足される
print(c + 2)

# 行列とベクトルの演算（ブロードキャスト）
# cの各行にベクトルaが足し合わされる。
print(c + a)
print(a + c) #どちらも同じ結果

# 行列同士の演算
print(c + c)


tensor([4, 5, 6])
tensor([5, 7, 9])
tensor([[8, 7, 6],
        [5, 4, 3]])
tensor([[7, 7, 7],
        [4, 4, 4]])
tensor([[7, 7, 7],
        [4, 4, 4]])
tensor([[12, 10,  8],
        [ 6,  4,  2]])


## 様々な値の計算
平均値、合計値、最大値、最小値など様々な値を計算する関数とメソッドが用意されています。


In [36]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6.]])

# 平均値を求める関数
m = torch.mean(a) # mはtensorのため、item()を使って要素を取り出す。
print(m.item())  # item()で値を取り出す

# 平均値を求めるメソッド
m = a.mean()
print(m.item())

# 列ごとの平均値 #0だと列、1だと行
print(a.mean(0))

# 合計値
print(torch.sum(a).item())

# 最大値
print(torch.max(a).item())

# 最小値
print(torch.min(a).item())


3.5
3.5
tensor([2.5000, 3.5000, 4.5000])
21.0
6.0
1.0
